// Generated by CoffeeScript 1.7.1
"use strict";
var Graph, Node, cool_dict, graph, graphs, node, node1;

graphs = {};

graphs.Graph = Graph = (function() {
  function Graph(nodes, edges) {
    this.nodes = nodes;
    this.edges = edges;
  }

  return Graph;

})();

graphs.Node = Node = (function() {
  function Node(data) {
    this.data = data;
  }

  return Node;

})();

graphs.Edge = Node = (function() {
  function Node(data) {
    this.data = data;
  }

  return Node;

})();

node = new graphs.Node({
  foo: "bar",
  id: 1
});

node1 = new graphs.Node({
  foo: "bar2",
  id: 2
});

graph = new graphs.Graph([node]);

console.log(graph.nodes);

cool_dict = {};

cool_dict[node] = 1;

cool_dict[node1] = 2;

console.log(cool_dict[node]);

console.log(cool_dict[node1]);
